### PR TITLE
typo fix turns into expanded longitude definition

### PR DESCRIPTION
**Pull request by jlivni**

### CODE REVIEW

**Comment by tmcw** [comment]
Sweet! Could you make the fix in README.md - `*.html` are all generated files

**Comment by jlivni** [comment]
"node build.js" updates the *.html but not README.md -- anything obvious I need to do before spending time debugging?

**Comment by tmcw** [comment]
`node build.js` basically takes README.md and generates `index.html` and all of the `section-foo.html` files - so changes need to start in the readme in order to propagate to the rest of the project

**Comment by tmcw** [comment]
(I will totally work on improving this process to make it less confusing, sorry)

**Comment by jlivni** [comment]
Ah I'm just an idiot and misread your first comment.  Derp.

**Comment by tmcw** [comment]
:+1: merged, thanks!

**Pull request merged**
